const styles = {
    container: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        alignItems: "center",
        justifyContent: "center",
    },
    text1: {
        position: "relative",
        marginLeft: 90,
        top: -50,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
    },
    text2: {
        color: "#000000",
        top: 80,
        right: 30,
        fontWeight: "700",
        fontSize: 28,
        width: 282,
        height: 42,
        backgroundColor: "#FFFFFF",
    },
    view1: {
        position: "absolute",
        width: 280,
        height: 45,
        left: -90,
        bottom: 80,
        borderWidth: 1,
        borderColor: "#676767",
        borderRadius: 10,
    },
    container1: {
        padding: 10,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderColor: '#FFD401',
        borderWidth: 1,
        borderRadius: 5,
        width: 310,
        height: 40,
        top: 60,
        zIndex: 10,
        backgroundColor: '#FFFFFF'
    },
    input: {
        left: 20,
        marginBottom: 0
    },
    icon: {
        width: 15,
        height: 15,
        tintColor: '#676767',
        left: 10
    },
    viewimage: {
        width: 24,
        height: 24,
        bottom: -28,
        right: 120,
        borderRadius: 100,
        overflow: 'hidden',
    },
    view2: {
        width: 11,
        height: 11,
        borderRadius: 100,
        backgroundColor: '#ED2552',
        bottom: 274,
        alignItems: 'center',
        justifyContent: 'center',
        left: 171
    },
    text6: {
        fontFamily: 'Poppins',
        fontWeight: '400',
        fontSize: 7,
        color: '#FFFFFF',
    },
    text4: {
        color: "#000000",
        right: 70,
        fontWeight: "400",
        fontSize: 12,
        bottom: 240,
    },
    text5: {
        color: "#000000",
        right: -150,
        fontWeight: "500",
        fontSize: 10,
        bottom: -20,
    },
    text3: {
        color: "#000000",
        right: 10,
        fontWeight: "700",
        fontSize: 20,
        bottom: 0,
    },
    viewschat: {
        width: 230,
        top: 45,
        left: 30,
        borderTopLeftRadius: 14,
        borderTopRightRadius: 14,
        borderBottomRightRadius: 14,
        borderBottomLeftRadius: 0,
        backgroundColor: '#FFD401',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 10,
        paddingBottom: 10,
        paddingRight: 8,
        paddingLeft: 8,
    },
    rectangleBox1: {
        backgroundColor: 'transparent',
        borderColor: 'rgba(255, 255, 255, 0)',
        borderWidth: 0,
        right: 350,
        top: 140,
        width: 320,
        height: 140,
    },
};

export default styles;