export const API_URLS = {
  GENERATE_OTP: 'api/generate_otp/',
  VERIFY_OTP: 'api/verify_otp/',
  SUGGESTION:'api/suggestion/',
  PROFLE_DETAIL: 'api/user-profile',
  LOGOUT: 'api/user-logout/',
  REGISTRATION: 'api/registration/',
  BELIEF: 'api/belief',
  INTEREST: 'api/interest',
  LANGUAGE: 'api/language',
  SEND_DATE_REQUEST: 'api/send-date-request/',
  GET_DATE_REQUEST: 'api/get-sent-request/',
  GET_VENUE: 'api/get-cities-venue/',
  UPDATE_DATE_REQUEST: 'api/update-request/ ',
  SAVE_USER: 'api/save-user/',
  UNSAVE_USER: 'api/unsave-user/',
  USER_SAVE_LIST:'api/user-save-list/',
  EDIT_DATE_CHOICE: 'api/edit-date-choice/',
  ADD_FUNDS: 'api/add-funds/',
  UPDATE_USER_PROFILE: 'api/update-user/',
  CHAT_LIST: 'api/user-chat-list/',
  VERIFY_MEET_OTP: 'api/verify-meet-otp/',
  GET_USER_DATE_CHAT_LIST: 'api/get-user-date-list/',
  DATE_EXTEND: 'api/date-extend/',
  GET_TRANSACTION_LIST:'api/get-transaction-list/'
 };